name: YouTube View Tracker

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  track-views:
    runs-on: ubuntu-latest
    env:
      YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }} 

    steps:
      - name: Code auschecken
        uses: actions/checkout@v3

      - name: Python einrichten
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Abhängigkeiten installieren
        run: |
          pip install -r requirements.txt

      - name: YouTube-Tracker ausführen
        run: |
          python Youtube-Tracker.py
          
      - name: Excel-Datei als Artefakt hochladen
        uses: actions/upload-artifact@v3
        with:
          name: video-views
          path: jp_views.xlsx
